#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidHUD.Resource", IsApplication=false)]

namespace AndroidHUD
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int barColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public static int barLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public static int barWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public static int circleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public static int delayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public static int radius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public static int rimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int rimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public static int spinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public static int text = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int textColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int textSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ic_errorstatus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_successstatus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int RoundedBg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int RoundedBgDark = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public static int LoadingImage = 2131034114;
			
			// aapt resource value: 0x7f050000
			public static int LoadingProgressBar = 2131034112;
			
			// aapt resource value: 0x7f050003
			public static int LoadingProgressWheel = 2131034115;
			
			// aapt resource value: 0x7f050001
			public static int textViewStatus = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int Loading = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int LoadingImage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int LoadingProgress = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public static int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public static int ProgressWheel_barColor = 3;
			
			// aapt resource value: 11
			public static int ProgressWheel_barLength = 11;
			
			// aapt resource value: 10
			public static int ProgressWheel_barWidth = 10;
			
			// aapt resource value: 8
			public static int ProgressWheel_circleColor = 8;
			
			// aapt resource value: 7
			public static int ProgressWheel_delayMillis = 7;
			
			// aapt resource value: 9
			public static int ProgressWheel_radius = 9;
			
			// aapt resource value: 4
			public static int ProgressWheel_rimColor = 4;
			
			// aapt resource value: 5
			public static int ProgressWheel_rimWidth = 5;
			
			// aapt resource value: 6
			public static int ProgressWheel_spinSpeed = 6;
			
			// aapt resource value: 0
			public static int ProgressWheel_text = 0;
			
			// aapt resource value: 1
			public static int ProgressWheel_textColor = 1;
			
			// aapt resource value: 2
			public static int ProgressWheel_textSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
